baseURL = "https://zbooyse.github.io"
languageCode = "en-gb"
title = "ZB"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Zoe Booyse - All rights reserved"

[params]
    # logo = "/images/author.jpg"
    description = "Portfolio"

[params.author]
    name = "Zoe Booyse"
    thumbnail = "/images/author.jpg"
    description = "Author of this essay."

[params.index]
    picture = "/images/author.jpg"
    title = "Zoe Booyse"
    subtitle = "Explorer of All Things Literary"
    mdtext = "Hi there, I am a third year English Literature and Drama student at the University of East Anglia. This website displays a selection of the essays that I have written during my time at UEA, as well as any other personal projects."
    alertbar = true

[params.social]
    github = "zbooyse"

# Menu

[[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 200
    url = "/"

[[menu.main]]
    name = "Academia"
    weight = 100
    identifier = "academia"
    url = "/academia"

[[menu.main]]
    name = "Projects"
    weight = 100
    identifier = "projects"
    url = "/projects"


# Example for static pages
# [[menu.main]]
#     name = "Imprint"
#     identifier = "imprint"
#     weight = 200
#     url = "/static/imprint"